### ISSUE TITLE
Installed in linux mint weird stuff happen

### ISSUE THREAD

**Issue by Minepool9** [isantop/kernelstub#36]
**Distribution :linux mint 21.1**
 
 
**Issue/Bug Description: makes apt stuff way longer**

**Steps to reproduce (if you know): do anything requiring apt**

**Expected behavior: doing sudo update should be done in at least a minute or so but what happens is i get this
 Traceback (most recent call last):
  File "/usr/bin/kernelstub", line 42, in <module>
    from kernelstub import mbapplication as application
ImportError: cannot import name 'mbapplication' from 'kernelstub' (/usr/local/lib/python3.10/dist-packages/kernelstub/__init__.py)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_kernelstub.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/kernelstub", line 42, in <module>
    from kernelstub import mbapplication as application
ImportError: cannot import name 'mbapplication' from 'kernelstub' (/usr/local/lib/python3.10/dist-packages/kernelstub/__init__.py)
run-parts: /etc/initramfs/post-update.d//zz-kernelstub exited with return code 1
dpkg: error processing package linux-firmware (--configure):
 installed linux-firmware package post-installation script subprocess returned error exit status 1
**

**Comment by Minepool9** [comment]
if someone please tell me how to remove kernel stub if i do do sudo apt remove nothing works
